name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.11.12
  - pip<=24.1.2
  - pip:
      - mlflow==2.22.0
      - cloudpickle==3.1.1
      - numpy==2.0.2
      - tensorflow==2.18.0
      - matplotlib
      - pandas