name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.10
        auto-update-conda: true
        use-mamba: true  # Lebih cepat dan efisien

    - name: Create conda environment from conda.yaml
      run: |
        eval "$(conda shell.bash hook)"
        mamba env create -f conda.yaml -n test-env || echo "env already exists"

    - name: Activate environment and install additional dependencies
      run: |
        eval "$(conda shell.bash hook)"
        conda activate test-env
        mamba install -y numpy pandas scikit-learn matplotlib

    - name: Print conda info
      run: |
        eval "$(conda shell.bash hook)"
        conda activate test-env
        conda info

    - name: List all conda environments
      run: |
        eval "$(conda shell.bash hook)"
        conda activate test-env
        conda env list

    - name: Run modelling script
      run: |
        eval "$(conda shell.bash hook)"
        conda activate test-env
        python modelling.py --data WEB_TRAFFIC_preprocessing.csv
