name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        auto-update-conda: true
        use-mamba: true

    - name: Create conda environment from conda.yaml
      run: |
        eval "$(conda shell.bash hook)"
        conda env create -f conda.yaml -n test-env

    - name: List conda environments after creation
      run: |
        eval "$(conda shell.bash hook)"
        conda env list

    - name: Activate environment and install additional dependencies
      run: |
        eval "$(conda shell.bash hook)"
        conda activate test-env
        mamba install -y numpy pandas scikit-learn matplotlib

    - name: Run modelling script
      run: |
        eval "$(conda shell.bash hook)"
        conda activate test-env
        python modelling.py --data WEB_TRAFFIC_preprocessing.csv
