name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.10
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env

      - name: Print conda info
        run: conda info

      - name: List all conda environments
        run: conda env list

      - name: Run modelling script
        run: python MLProject/modelling.py
