name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: MLProject/conda.yaml
        activate-environment: mlflow-env
        python-version: 3.10

    - name: Run modelling.py
      run: |
        python modelling.py
