name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.10
        auto-update-conda: true
        activate-environment: test-env
        environment-name: test-env
        use-mamba: true

    - name: Install dependencies
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate test-env
        mamba install numpy pandas scikit-learn matplotlib -y

    - name: Print conda info
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate test-env
        conda info

    - name: List all conda environments
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate test-env
        conda env list

    - name: Run modelling script
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate test-env
        python MLProject/modelling.py
